# Generated by Django 3.2 on 2021-05-07 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=100)),
                ('article', models.CharField(max_length=5000)),
                ('date_limite', models.DateField()),
                ('admin_only', models.BooleanField()),
            ],
        ),
    ]
