# Generated by Django 3.1.2 on 2021-05-07 11:51

from datetime import datetime
from django.db import migrations, models
import datetime

class Migration(migrations.Migration):

    dependencies = [
        ('article_creation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='post',
            name='limit_date',
            field=models.DateTimeField(default=datetime.datetime.now()),
            preserve_default=False,
        ),
    ]
